#!/bin/bash
#Desc: This script wil log only defined keywords

tail -fn0 /var/log/messages | while read line
do
echo $line | egrep -i "refused|invalid|error|fail|shut|down|offline"
	if [ $? = 0 ]
	then
	echo $line >> /tmp/filtered_Thanos_messages
	fi
done

