#!/bin/bash
#Author: Thanos
#Date Created: 03/28/2020
#Desc: This will run basic admin tasks
echo
echo This script will run basic administrative tasks
echo
top | head -10
echo
df -h
echo
free -m
echo
uptime
echo iostat
echo
echo End of tasks

